/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as pagesNot_found_pageRouteImport } from './routes/(pages)/not_found_page'
import { Route as pagesDashboardRouteRouteImport } from './routes/(pages)/dashboard/route'
import { Route as pagesDashboardAdd_todoRouteImport } from './routes/(pages)/dashboard/add_todo'
import { Route as pagesDashboardEdit_todoIdRouteImport } from './routes/(pages)/dashboard/edit_todo.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesNot_found_pageRoute = pagesNot_found_pageRouteImport.update({
  id: '/(pages)/not_found_page',
  path: '/not_found_page',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesDashboardRouteRoute = pagesDashboardRouteRouteImport.update({
  id: '/(pages)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesDashboardAdd_todoRoute = pagesDashboardAdd_todoRouteImport.update({
  id: '/add_todo',
  path: '/add_todo',
  getParentRoute: () => pagesDashboardRouteRoute,
} as any)
const pagesDashboardEdit_todoIdRoute =
  pagesDashboardEdit_todoIdRouteImport.update({
    id: '/edit_todo/$id',
    path: '/edit_todo/$id',
    getParentRoute: () => pagesDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof pagesDashboardRouteRouteWithChildren
  '/not_found_page': typeof pagesNot_found_pageRoute
  '/dashboard/add_todo': typeof pagesDashboardAdd_todoRoute
  '/dashboard/edit_todo/$id': typeof pagesDashboardEdit_todoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof pagesDashboardRouteRouteWithChildren
  '/not_found_page': typeof pagesNot_found_pageRoute
  '/dashboard/add_todo': typeof pagesDashboardAdd_todoRoute
  '/dashboard/edit_todo/$id': typeof pagesDashboardEdit_todoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(pages)/dashboard': typeof pagesDashboardRouteRouteWithChildren
  '/(pages)/not_found_page': typeof pagesNot_found_pageRoute
  '/(pages)/dashboard/add_todo': typeof pagesDashboardAdd_todoRoute
  '/(pages)/dashboard/edit_todo/$id': typeof pagesDashboardEdit_todoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/not_found_page'
    | '/dashboard/add_todo'
    | '/dashboard/edit_todo/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/not_found_page'
    | '/dashboard/add_todo'
    | '/dashboard/edit_todo/$id'
  id:
    | '__root__'
    | '/'
    | '/(pages)/dashboard'
    | '/(pages)/not_found_page'
    | '/(pages)/dashboard/add_todo'
    | '/(pages)/dashboard/edit_todo/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  pagesDashboardRouteRoute: typeof pagesDashboardRouteRouteWithChildren
  pagesNot_found_pageRoute: typeof pagesNot_found_pageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/not_found_page': {
      id: '/(pages)/not_found_page'
      path: '/not_found_page'
      fullPath: '/not_found_page'
      preLoaderRoute: typeof pagesNot_found_pageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/dashboard': {
      id: '/(pages)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof pagesDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/dashboard/add_todo': {
      id: '/(pages)/dashboard/add_todo'
      path: '/add_todo'
      fullPath: '/dashboard/add_todo'
      preLoaderRoute: typeof pagesDashboardAdd_todoRouteImport
      parentRoute: typeof pagesDashboardRouteRoute
    }
    '/(pages)/dashboard/edit_todo/$id': {
      id: '/(pages)/dashboard/edit_todo/$id'
      path: '/edit_todo/$id'
      fullPath: '/dashboard/edit_todo/$id'
      preLoaderRoute: typeof pagesDashboardEdit_todoIdRouteImport
      parentRoute: typeof pagesDashboardRouteRoute
    }
  }
}

interface pagesDashboardRouteRouteChildren {
  pagesDashboardAdd_todoRoute: typeof pagesDashboardAdd_todoRoute
  pagesDashboardEdit_todoIdRoute: typeof pagesDashboardEdit_todoIdRoute
}

const pagesDashboardRouteRouteChildren: pagesDashboardRouteRouteChildren = {
  pagesDashboardAdd_todoRoute: pagesDashboardAdd_todoRoute,
  pagesDashboardEdit_todoIdRoute: pagesDashboardEdit_todoIdRoute,
}

const pagesDashboardRouteRouteWithChildren =
  pagesDashboardRouteRoute._addFileChildren(pagesDashboardRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  pagesDashboardRouteRoute: pagesDashboardRouteRouteWithChildren,
  pagesNot_found_pageRoute: pagesNot_found_pageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
